In [5]:
import torch
import numpy as np

path = "/p1/data/jtian/SA/05_CAST/output_all/30_align_to_15_coords_final.data"

coords = torch.load(path, map_location="cpu")
print("loaded type:", type(coords))

if isinstance(coords, dict):
    print(coords.keys())
    first_key = list(coords.keys())[0]
    print(coords[first_key].shape)
    print(coords[first_key][:30])
    print(coords['15'][:30])
else:
    print(coords.shape)


loaded type: <class 'dict'>
dict_keys(['30', '15'])
torch.Size([45217, 2])
tensor([[ 50.9024,  31.4117],
        [ 56.6226,  34.4029],
        [ 62.0396,  36.8887],
        [ 67.1827,  38.9561],
        [ 72.1341,  40.6656],
        [ 76.9324,  42.0381],
        [ 81.7122,  43.1011],
        [ 86.5843,  43.8291],
        [ 91.7351,  44.1890],
        [-20.1390, -49.4487],
        [-12.7351, -37.6562],
        [ -5.1750, -26.4848],
        [  2.4898, -16.0942],
        [ 10.2801,  -6.6010],
        [ 18.1355,   1.9424],
        [ 25.9778,   9.4405],
        [ 33.6785,  15.8814],
        [ 41.1607,  21.2881],
        [ 48.3162,  25.7320],
        [ 55.0994,  29.3433],
        [ 61.4505,  32.2242],
        [ 67.3914,  34.5035],
        [ 72.9375,  36.3037],
        [ 78.1626,  37.6870],
        [ 83.1040,  38.7505],
        [ 87.8628,  39.5064],
        [ 92.5181,  39.9815],
        [ 97.2295,  40.1416],
        [102.1653,  39.9410],
        [107.4827,  39.2510]])
[[   0.    0.]
 [  20.  

In [7]:

path = "/p1/data/jtian/SA/05_CAST/output_old/15_align_to_0_coords_final.data"

coords = torch.load(path, map_location="cpu")
print("loaded type:", type(coords))

if isinstance(coords, dict):
    print(coords.keys())
    first_key = list(coords.keys())[0]
    print(coords[first_key].shape)
    print(coords[first_key][:30])
    print(coords['0'][:30])
else:
    print(coords.shape)

loaded type: <class 'dict'>
dict_keys(['15', '0'])
torch.Size([53409, 2])
tensor([[50427.3164,  -273.8949],
        [50407.7344,  -274.7972],
        [50388.1523,  -275.6996],
        [50368.5742,  -276.6022],
        [50348.9922,  -277.5045],
        [50329.4102,  -278.4069],
        [50309.8281,  -279.3092],
        [50290.2500,  -280.2118],
        [50270.6680,  -281.1141],
        [50251.0859,  -282.0165],
        [50524.3672,  -250.7867],
        [50504.7852,  -251.6891],
        [50485.2031,  -252.5914],
        [50465.6211,  -253.4940],
        [50446.0391,  -254.3963],
        [50426.4609,  -255.2987],
        [50406.8789,  -256.2010],
        [50387.2969,  -257.1034],
        [50367.7148,  -258.0060],
        [50348.1328,  -258.9083],
        [50328.5547,  -259.8107],
        [50308.9727,  -260.7130],
        [50289.3906,  -261.6156],
        [50269.8086,  -262.5179],
        [50250.2305,  -263.4203],
        [50230.6484,  -264.3226],
        [50211.0664,  -265.2252],
        

In [19]:
import torch
import numpy as np

path = "/p1/data/jtian/SA/05_CAST/output_old/15_align_to_0_coords_final.data"
coords = torch.load(path, map_location="cpu")

first_key = list(coords.keys())[0]
A = coords[first_key].cpu().numpy()
B = coords["0"]
# 把前30个点转成可哈希的 tuple
# A30 = [tuple(x) for x in A[:30]]
# B30 = [tuple(x) for x in B[:30]]

# setA = set(A30)
# setB = set(B30)

# overlap = sorted(list(setA & setB))
# print("exact overlap count:", len(overlap))
# print("exact overlap points:")
# for p in overlap:
#     print(p)
import numpy as np
from sklearn.neighbors import NearestNeighbors

tol = 6 # 你可以改大一点，比如 0.5 / 1 / 2（看你坐标尺度）
A30 = A
B30 = B

nn = NearestNeighbors(n_neighbors=1).fit(B30)
dist, idx = nn.kneighbors(A30)
dist = dist[:,0]
idx = idx[:,0]

mask = dist <= tol
print("approx overlap count:", int(mask.sum()), " / ", len(A30), " (tol=", tol, ")")

print("\nMatched pairs (A_index, B_index, dist, A_point, B_point):")
for i in np.where(mask)[0]:
    j = idx[i]
    print(i, j, dist[i], A30[i], B30[j])


approx overlap count: 13720  /  53409  (tol= 6 )

Matched pairs (A_index, B_index, dist, A_point, B_point):
1251 47377 5.343523363620194 [5.0237375e+04 1.5522105e+01] [5.02398086e+04 1.07649145e+01]
1360 47356 5.646439228731537 [5.0256098e+04 3.5020641e+01] [5.02598086e+04 3.07649136e+01]
1361 47355 4.699875270715256 [5.0236516e+04 3.4118298e+01] [5.02398086e+04 3.07649136e+01]
1362 47354 3.7779919792244727 [5.0216934e+04 3.3215954e+01] [5.02198086e+04 3.07649136e+01]
1363 47353 2.900952779769223 [5.0197355e+04 3.2313366e+01] [5.01998086e+04 3.07649136e+01]
1364 47352 2.135255797371942 [5.0177773e+04 3.1411022e+01] [5.01798086e+04 3.07649136e+01]
1365 47351 1.6373612454957656 [5.0158191e+04 3.0508678e+01] [5.01598086e+04 3.07649136e+01]
1366 47350 1.6674623277824454 [5.0138609e+04 2.9606335e+01] [5.01398086e+04 3.07649136e+01]
1367 47349 2.2028780565024864 [5.0119031e+04 2.8703747e+01] [5.01198086e+04 3.07649136e+01]
1368 47348 2.9852210894837308 [5.0099449e+04 2.7801403e+01] [5.009980

In [20]:


path = "/p1/data/jtian/SA/05_CAST/output_cast9/15_align_to_0_coords_final.data"
coords = torch.load(path, map_location="cpu")
print("loaded type:", type(coords))

if isinstance(coords, dict):
    print(coords.keys())
    first_key = list(coords.keys())[0]
    print(coords[first_key].shape)
    print(coords[first_key][:30])
    print(coords['0'][:30])
else:
    print(coords.shape)

loaded type: <class 'dict'>
dict_keys(['15', '0'])
torch.Size([53409, 2])
tensor([[50493.7344,  -227.9748],
        [50473.9727,  -228.4689],
        [50454.2109,  -228.9628],
        [50434.4531,  -229.4569],
        [50414.6914,  -229.9508],
        [50394.9297,  -230.4450],
        [50375.1680,  -230.9391],
        [50355.4062,  -231.4330],
        [50335.6445,  -231.9272],
        [50315.8867,  -232.4213],
        [50592.0820,  -207.2445],
        [50572.3242,  -207.7387],
        [50552.5625,  -208.2326],
        [50532.8008,  -208.7267],
        [50513.0391,  -209.2206],
        [50493.2773,  -209.7148],
        [50473.5156,  -210.2089],
        [50453.7578,  -210.7028],
        [50433.9961,  -211.1969],
        [50414.2344,  -211.6908],
        [50394.4727,  -212.1850],
        [50374.7109,  -212.6791],
        [50354.9492,  -213.1730],
        [50335.1914,  -213.6671],
        [50315.4297,  -214.1613],
        [50295.6680,  -214.6552],
        [50275.9062,  -215.1493],
        

In [21]:
import torch
import numpy as np

path = "/p1/data/jtian/SA/05_CAST/output_cast9/15_align_to_0_coords_final.data"
coords = torch.load(path, map_location="cpu")

first_key = list(coords.keys())[0]
A = coords[first_key].cpu().numpy()
B = coords["0"]
# 把前30个点转成可哈希的 tuple
# A30 = [tuple(x) for x in A[:30]]
# B30 = [tuple(x) for x in B[:30]]

# setA = set(A30)
# setB = set(B30)

# overlap = sorted(list(setA & setB))
# print("exact overlap count:", len(overlap))
# print("exact overlap points:")
# for p in overlap:
#     print(p)
import numpy as np
from sklearn.neighbors import NearestNeighbors

tol = 6 # 你可以改大一点，比如 0.5 / 1 / 2（看你坐标尺度）
A30 = A
B30 = B

nn = NearestNeighbors(n_neighbors=1).fit(B30)
dist, idx = nn.kneighbors(A30)
dist = dist[:,0]
idx = idx[:,0]

mask = dist <= tol
print("approx overlap count:", int(mask.sum()), " / ", len(A30), " (tol=", tol, ")")

print("\nMatched pairs (A_index, B_index, dist, A_point, B_point):")
for i in np.where(mask)[0]:
    j = idx[i]
    print(i, j, dist[i], A30[i], B30[j])


approx overlap count: 14091  /  53409  (tol= 6 )

Matched pairs (A_index, B_index, dist, A_point, B_point):
1121 47341 5.326453519566267 [50743.78      52.3475] [5.0739e+04 5.0000e+01]
1122 47340 5.350760168146819 [50724.02       51.85336] [5.0719e+04 5.0000e+01]
1123 47339 5.430721059055381 [50704.258       51.359463] [5.0699e+04 5.0000e+01]
1124 47338 5.5637962640718674 [50684.496       50.865322] [5.0679e+04 5.0000e+01]
1125 47337 5.7502894450391455 [5.0664738e+04 5.0371426e+01] [5.0659e+04 5.0000e+01]
1126 47336 5.977822202669837 [5.0644977e+04 4.9877285e+01] [5.0639e+04 5.0000e+01]
1225 47297 4.2443019376744475 [50822.367       72.583824] [50819.    70.]
1226 47296 4.170655243187165 [50802.61       72.08968] [50799.    70.]
1227 47295 4.165359022764209 [50782.848      71.59554] [50779.    70.]
1228 47294 4.231844762743988 [50763.086      71.10165] [50759.    70.]
1229 47293 4.366684221794392 [50743.324       70.607506] [50739.    70.]
1230 47292 4.56390818405962 [50723.562       7